[renderer]
fog=true
fog_start=1200
distance_max=1300
enable_hm_filtering=false

[screen]
width=1920
height=1080

[map]
heightmap="hm.png"
texture="tx.png"

[player]
height=25
speed=2
sensitivity_x=2
sensitivity_y=8